name: CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: docker pull 3384824840amora/atv-comp:latest

      - name: Stop Docker container
        run: docker stop atv-comp || true

      - name: Remove Docker container
        run: docker rm atv-comp || true

      - name: Run Docker container
        run: docker run -d -p 8080:8080 --name atv-comp 3384824840amora/atv-comp:latest